Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,11 +7,12 @@ on:
   workflow_dispatch:
   repository_dispatch:
     types: [new_url_received]
+
 jobs:
   download_and_release:
     runs-on: ubuntu-latest
     permissions:
-      contents: write # Diperlukan untuk membuat rilis GitHub
+      contents: write
 
     steps:
     - name: Checkout code
@@ -34,6 +35,8 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
+        pip install yt-dlp
+        pip install requests
 
     - name: Set MediaFire Page URL as environment variable
       run: |
@@ -42,21 +45,19 @@ jobs:
     - name: Run MediaFire Downloader Script
       run: python download_mediafire.py
 
-    - name: Get Download URL and Filename
+    - name: Get Downloaded Filename
       id: get_filename
       run: |
-        DOWNLOAD_URL=$(cat download_link.txt)
-        FILE_NAME=$(basename "$DOWNLOAD_URL")
+        if [ ! -f "downloaded_filename.txt" ]; then
+          echo "Error: downloaded_filename.txt not found. Exiting."
+          exit 1
+        fi
+        FILE_NAME=$(cat downloaded_filename.txt)
         echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
       shell: bash
 
-    - name: Download File if not already released
-      run: |
-        DOWNLOAD_URL=$(cat download_link.txt)
-        wget -O "$FILE_NAME" "$DOWNLOAD_URL"
-      shell: bash
-
     - name: Create GitHub Release
+      
       uses: softprops/action-gh-release@v1
       with:
         tag_name: release-${{ github.run_number }}
@@ -64,6 +65,6 @@ jobs:
         body: |
           Rilis otomatis dari MediaFire.
           File: ${{ steps.get_filename.outputs.file_name }}
-        files: ${{ steps.get_filename.outputs.file_name }}
+        files: ${{ steps.get_filename.outputs.file_name }} # Ini yang diubah
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
